### PR TITLE
parallelize ALSDemo.jl

### PR DESCRIPTION
**Pull request by tanmaykm**
using shared arrays for now to get single machine parallelism.

### CODE REVIEW

**Comment by ViralBShah** [comment]
What is the speedup?

**Comment by abhijithch** [comment]
For 20 million ratings,
 single proc - ~450sec
 3 procs - ~350sec.

**Comment by tanmaykm** [comment]
Should be possible to get even more speedup.
Noticed just now that `update_movie` is not returning a `Void`, which could be affecting performance. Could you run once more after changing `update_movie` to return `nothing`?

Also thinking of separating out an init phase to exchange the shared variables only once, and using a simple read-only shared dict.

**Comment by ViralBShah** [comment]
I think the benchmarking is not correct.

**Pull request merged**
